### 
POST http://localhost:3000/api/users HTTP/1.1
Content-Type:application/json 

{


    
    "nombre": "Simon",
    "enlace": "saimon@gr",
    "empresa": "HUAWEI",
    "mision": "ROMPER LAS PELOTAS",
    "genero": "MASCULINO",
    "protagonista": "PERRUNO",
    "objetivo": "AMIGO FIEL",
    "motivacion": "LA COMIDA",
    "malo": "JACK",
    "ayudante": "PIA",
    "actitud": "AMOROSA",
    "mensaje": "LOS AMIGOS SIEMPRE UNIDS",
    "comportamiento": "DEFENSIVO",
    "responseAI": ""
}


###
GET http://localhost:3000/api/users HTTP/1.1

###
GET http://localhost:3000/api/user/654c338cdd89c487fc4e8611 HTTP/1.1

###
PUT http://localhost:3000/api/users/6563ec761cb2e991e789a4d8 HTTP/1.1
Content-Type:application/json 

{
    "nombre": "Jack",
    "enlace": "saimon@gr",
    "empresa": "HUAWEI",
    "mision": "ROMPER LAS guindas",
    "genero": "dudoso",
    "protagonista": "PERRUNO",
    "objetivo": "AMIGO FIEL",
    "motivacion": "LA COMIDA",
    "malo": "JACK",
    "ayudante": "PIA",
    "actitud": "AMOROSA",
    "mensaje": "LOS AMIGOS SIEMPRE UNIDS",
    "comportamiento": "DEFENSIVO",
    "responseAI": ""
}
 

###
DELETE http://localhost:3000/api/users/6654c1d6e1c48a3994bdf83c6 HTTP/1.1
