###
Send Request
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
  "nombre": "Mb",
	"enlace": "mari@ejemplo.com",
	"genero": "fem",
	"protagonista": "heroe",
	"objetivo": "emigrar",
	"malo": "el gobierno",
	"ayudante": "estudio",
	"actitud": "student"

}

### 
GET http://localhost:3000/users HTTP/1.1

###
DELETE http://localhost:3000/user/6454907a716ec753c0892418/delete HTTP/1.1